[build]
  base = "/"
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NETLIFY_CACHE_DIR = "false"

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173
